"""add uniqconstraint for appointment

Revision ID: f4ae0d316e82
Revises: 6551d14260e5
Create Date: 2026-02-22 16:20:20.722899

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f4ae0d316e82"
down_revision: Union[str, Sequence[str], None] = "6551d14260e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("appointment_uniq"), "appointments", type_="unique"
    )
    op.create_unique_constraint(
        "client_appointment_uniq", "appointments", ["client_id", "start_time"]
    )
    op.create_unique_constraint(
        "executor_appointment_uniq",
        "appointments",
        ["executor_id", "start_time"],
    )
    op.create_unique_constraint(None, "appointments", ["id"])
    op.create_unique_constraint(None, "clients", ["id"])
    op.create_unique_constraint(None, "executors", ["id"])
    op.create_unique_constraint(None, "services", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "services", type_="unique")
    op.drop_constraint(None, "executors", type_="unique")
    op.drop_constraint(None, "clients", type_="unique")
    op.drop_constraint(None, "appointments", type_="unique")
    op.drop_constraint(
        "executor_appointment_uniq", "appointments", type_="unique"
    )
    op.drop_constraint(
        "client_appointment_uniq", "appointments", type_="unique"
    )
    op.create_unique_constraint(
        op.f("appointment_uniq"),
        "appointments",
        ["executor_id", "start_time"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
